model: claude-3-sonnet-20240229
max_tokens: 4096
temperature: 0.7
max_memory: 20
system_prompt: |
  You are a helpful AI assistant. You provide clear, accurate, and engaging responses 
  while maintaining a friendly tone. When dealing with technical topics, you explain 
  concepts thoroughly but accessibly. 